language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: gPMFjbnWUTfe0qELvi7PL32p4BDcdSL3H/Y2++u3yuovDeAkKq+rTWHZa9KBHdwNhLRMqUi0PqH3UpB/cRi3LvH7Zc+MO/gXMHjtA6u6MaPVZ2KyyceQ2/XHmLZBOCUoamtVj51FHn+jfA0EpVYDIrgKJBKtnUgnKSK8QBTqAyulahxUgUJODAJo5gPWLJiiDj0Xtwb2VkE9SF9KLEFUbMAp0xwHBHq55LhY5y3Wa1i34iy/oJ1+pmboi7R32dlej5ixW/EQ/7oEgElA+043tKBEYWTmPxeAHcD/WUJZE62/mprhBXDct2AdDMkqr1rkYDv13SKyd0wL/QX7y7LeKjKcJB05LMuhbIoCqJ0ZCStPDGrXRpM93ubSlVeDD8EvhdSz+aUMzbexrfPX8rRJnDnTnloEDeH2d0Sa1pRaFUszs1UZN0gWYQ/zKsoeyuMZc0h635ypfMUKpbGRXKe7UPOavHyDdROwGW0A0ZMkE0lcdx/moPPXgAp1HFp22+hiAA9jVsoOv87kxEUT76cnTczOz2SV4DY7qawENF0lvasx6sceGmnDI3IxUVOWFX6dMNFj+OURNOKW982/I6uyvrPm//d86pfAoNOKx6OKAGjn3mDmmaZh+V65fFU8wZsxQj1VTTG9sCYHE+mr5zihDKhGAvVGd+lDmL1cCGrSrQw=
  app: protected-garden-37267
  on:
    repo: cafreeman/peepchat-api
